__version__ = '0.1.0'
__title__ = "digital-document-checker"
__description__ = "Parsing, verificação e validação de documentos digitais brasileiros (CNH e outros) via QRCode."
__url__ = "https://github.com/helviojunior/digital-document-checker"
__build__ = 0x000000
__author__ = "Helvio Junior  (M4v3r1ck)"
__author_email__ = "helvio_junior@hotmail.com"
__license__ = "MIT"
__copyright__ = "Copyright Helvio Junior"
